spring.application.name=solontax-g1-management-kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.retry.topic.attempts=3
kafka.retry.topic.multiplier=1.0
kafka.retry.topic.initial.interval=1000
logging.level.root=INFO